# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter


gem "minitest", "~>3.2", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "racc", ">=1.4.6", :group => [:development, :test]
gem "rdoc", "~>3.11", :group => [:development, :test]
gem "json", ">=0", :group => [:development, :test]
gem "hoe", "~>3.0", :group => [:development, :test]

# vim: syntax=ruby
